name: ML_Pipeline

on:
  push:
    branches:
      - main  # Executa o pipeline sempre que houver mudanças na branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # Define o ambiente da máquina virtual do GitHub

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3  # Baixa o código do repositório

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Versão do Python a ser usada

    - name: Instalar Dependências
      run: |
        pip install -r requirements.txt  # Instala pacotes do projeto

    - name: Executar Pré-processamento
      run: python preprocessamento.py  # Executa o script de pré-processamento

    - name: Treinar Modelo
      run: python treinamento.py  # Executa o treinamento do modelo

    - name: Fazer Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Criar e Publicar Imagem Docker
      run: |
        docker build -t seu-usuario/ml-model .
        docker tag seu-usuario/ml-model seu-usuario/ml-model:latest
        docker push seu-usuario/ml-model:latest

